name: UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:4.21.0-20240507
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g
          --health-cmd="curl -f http://localhost:4444/wd/hub/status || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: 📥 Repo'yu çek
        uses: actions/checkout@v3

      - name: ☕ Java'yı kur
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 📦 Maven ile testleri çalıştır
        run: mvn clean test
        working-directory: ui-tests